jdbc.driver=${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
jdbc.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:buttie}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
jdbc.username=${MYSQL_USER:root}
jdbc.password=${MYSQL_PASSWORD:}

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

redis.port=${REDIS_PORT}
redis.host=${REDIS_HOST}

crypto.secret=${CRYPTO_SECRET}
crypto.algorithm=${CRYPTO_ALGORITHM:AES}

portone.api.key=${PORTONE_API_KEY}