-- V9에서 제거된 CARD 테이블 복구 및 거래 원천/분류 구조 추가
CREATE TABLE IF NOT EXISTS `CARD` (
    `CARD_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `LINKED_ACCOUNT_ID` BIGINT NULL,
    `LINKED_BANK_CODE` VARCHAR(8) NULL,
    `EXTERNAL_CARD_ID` VARCHAR(100) NOT NULL,
    `CARD_INSTITUTION_NAME` VARCHAR(100) NOT NULL,
    `CARD_NAME` VARCHAR(100) NOT NULL,
    `CARD_TYPE` ENUM('CREDIT', 'DEBIT', 'PREPAID') NOT NULL,
    `CARD_NUMBER_MASKED` VARCHAR(50) NULL,
    `CARD_BALANCE` INT NOT NULL DEFAULT 0,
    `CARD_IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `CARD_SYNCED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`CARD_ID`),
    UNIQUE KEY `UK_CARD_USER_EXTERNAL` (`USER_ID`, `EXTERNAL_CARD_ID`),
    KEY `IDX_CARD_IS_ACTIVE` (`CARD_IS_ACTIVE`),
    KEY `IDX_CARD_LINKED_ACCOUNT_ID` (`LINKED_ACCOUNT_ID`),

    CONSTRAINT `FK_CARD_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_CARD_LINKED_ACCOUNT`
        FOREIGN KEY (`LINKED_ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

ALTER TABLE `TRANSACTION`
    ADD COLUMN `CARD_ID` BIGINT NULL AFTER `ACCOUNT_ID`,
    ADD COLUMN `TRANSACTION_SOURCE`
        ENUM('ACCOUNT', 'CARD', 'MANUAL') NOT NULL DEFAULT 'MANUAL'
        AFTER `EXTERNAL_TRANSACTION_ID`,
    ADD COLUMN `CLASSIFICATION_METHOD`
        ENUM('MERCHANT_REGNO', 'MERCHANT_CATEGORY_CODE', 'ACCOUNT_INFLOW',
             'USER_CONFIRMED', 'UNCLASSIFIED', 'MANUAL')
        NOT NULL DEFAULT 'MANUAL'
        AFTER `TRANSACTION_SOURCE`,
    ADD COLUMN `MERCHANT_NAME` VARCHAR(100) NULL
        AFTER `CLASSIFICATION_METHOD`,
    ADD COLUMN `MERCHANT_REGNO` VARCHAR(20) NULL
        AFTER `MERCHANT_NAME`,
    ADD COLUMN `MERCHANT_CATEGORY_CODE` VARCHAR(20) NULL
        AFTER `MERCHANT_REGNO`,
    ADD COLUMN `ANALYSIS_EXCLUDED` BOOLEAN NOT NULL DEFAULT FALSE
        AFTER `TRANSACTION_MEMO`,
    MODIFY COLUMN `TRANSACTION_TYPE`
        ENUM('EXPENSE', 'INCOME', 'FIXED', 'TRANSFER') NOT NULL,
    MODIFY COLUMN `EXPENSE_CATEGORY`
        ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'COMMUNICATION',
             'SUBSCRIPTION', 'EDUCATION', 'CERTIFICATE', 'ETC_EXPENSE') NULL,
    ADD KEY `IDX_TRANSACTION_CARD_ID` (`CARD_ID`),
    ADD UNIQUE KEY `UK_TRANSACTION_CARD_EXTERNAL`
        (`CARD_ID`, `EXTERNAL_TRANSACTION_ID`),
    ADD KEY `IDX_TRANSACTION_SOURCE` (`TRANSACTION_SOURCE`),
    ADD KEY `IDX_TRANSACTION_ANALYSIS_EXCLUDED` (`ANALYSIS_EXCLUDED`),
    ADD CONSTRAINT `FK_TRANSACTION_CARD`
        FOREIGN KEY (`CARD_ID`) REFERENCES `CARD` (`CARD_ID`)
        ON UPDATE CASCADE ON DELETE SET NULL;
