-- DUE_DATE 널 허용 (온통청년 API에 마감일 없는 정책 다수 존재)
ALTER TABLE `POLICY` MODIFY `DUE_DATE` DATETIME NULL;

-- 외부 API 연동 식별 컬럼 (재수집 시 upsert 판단용)
ALTER TABLE `POLICY`
    ADD COLUMN `EXTERNAL_SOURCE` VARCHAR(30) NULL COMMENT '수집 출처 (YOUTHCENTER 등)',
    ADD COLUMN `EXTERNAL_POLICY_ID` VARCHAR(50) NULL COMMENT '원본 API 정책번호 (plcyNo 등)',
    ADD UNIQUE KEY `UK_POLICY_EXTERNAL` (`EXTERNAL_SOURCE`, `EXTERNAL_POLICY_ID`);

-- 지원금액 자동파싱 신뢰도 (관리자 검수 대상 구분용)
ALTER TABLE `POLICY`
    ADD COLUMN `AMOUNT_PARSE_CONFIDENCE` ENUM('HIGH', 'LOW', 'MANUAL') NOT NULL DEFAULT 'MANUAL'
        COMMENT '지원금액/개월수 자동파싱 신뢰도. LOW/MANUAL은 관리자 확인 필요';

-- 다지역 정책 처리 (zipCd가 콤마로 여러 개 오는 경우 대응)
CREATE TABLE `POLICY_REGION_MAP` (
    `POLICY_REGION_MAP_ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `POLICY_ID` BIGINT NOT NULL,
    `ZIP_CD` VARCHAR(10) NOT NULL,
    `REGION_NAME` VARCHAR(50) NULL,
    FOREIGN KEY (`POLICY_ID`) REFERENCES `POLICY` (`POLICY_ID`),
    UNIQUE KEY `UK_POLICY_ZIP` (`POLICY_ID`, `ZIP_CD`)
);
