ALTER TABLE `TRANSACTION`
    MODIFY COLUMN `EXPENSE_CATEGORY`
        ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'COMMUNICATION',
             'SUBSCRIPTION', 'EDUCATION', 'CERTIFICATE', 'ETC_EXPENSE',
             'ALCOHOL_ENTERTAINMENT', 'CAFE_SNACK', 'JOB_PREPARATION', 'SHOPPING',
             'HOBBY_LEISURE', 'HOUSING_COMMUNICATION', 'TRANSPORT_FUEL',
             'HEALTH_FITNESS', 'OTHER_FINANCE') NULL;

ALTER TABLE `SIMULATION_ITEM`
    MODIFY COLUMN `SIMULATION_ITEM_EXPENSE_CATEGORY`
        ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'COMMUNICATION',
             'SUBSCRIPTION', 'EDUCATION', 'CERTIFICATE', 'ETC_EXPENSE',
             'ALCOHOL_ENTERTAINMENT', 'CAFE_SNACK', 'JOB_PREPARATION', 'SHOPPING',
             'HOBBY_LEISURE', 'HOUSING_COMMUNICATION', 'TRANSPORT_FUEL',
             'HEALTH_FITNESS', 'OTHER_FINANCE') NULL;

UPDATE `TRANSACTION`
SET `EXPENSE_CATEGORY` = CASE
    WHEN `TRANSACTION_TYPE` IN ('INCOME', 'TRANSFER') THEN NULL
    WHEN `TRANSACTION_CONTENT` REGEXP '스타벅스|메가커피|스무디킹|투썸|이디야|컴포즈|설빙|배스킨라빈스|파리바게뜨' THEN 'CAFE_SNACK'
    WHEN `TRANSACTION_CONTENT` REGEXP '토익|텝스|오픽|한국사|컴퓨터활용능력|정보처리기사|자격증|인강|온라인 강의|전공서적|스터디카페' THEN 'JOB_PREPARATION'
    WHEN `TRANSACTION_CONTENT` REGEXP '다이소|올리브영|미용실|세탁소|반려동물|편의점 생필품' THEN 'SHOPPING'
    WHEN `TRANSACTION_CONTENT` REGEXP '약국|병원|헬스장|실비보험' THEN 'HEALTH_FITNESS'
    WHEN `TRANSACTION_CONTENT` REGEXP '넷플릭스|디즈니플러스|왓챠|멜론|유튜브 프리미엄|리디셀렉트|밀리의 서재|문화상품권|서점 도서' THEN 'HOBBY_LEISURE'
    WHEN `EXPENSE_CATEGORY` IN ('HOUSING', 'COMMUNICATION') THEN 'HOUSING_COMMUNICATION'
    WHEN `EXPENSE_CATEGORY` = 'TRANSPORT' THEN 'TRANSPORT_FUEL'
    WHEN `EXPENSE_CATEGORY` IN ('EDUCATION', 'CERTIFICATE') THEN 'JOB_PREPARATION'
    WHEN `EXPENSE_CATEGORY` = 'SUBSCRIPTION' THEN 'HOBBY_LEISURE'
    WHEN `EXPENSE_CATEGORY` = 'ETC_EXPENSE' THEN 'OTHER_FINANCE'
    ELSE `EXPENSE_CATEGORY`
END;

UPDATE `SIMULATION_ITEM`
SET `SIMULATION_ITEM_EXPENSE_CATEGORY` = CASE `SIMULATION_ITEM_EXPENSE_CATEGORY`
    WHEN 'TRANSPORT' THEN 'TRANSPORT_FUEL'
    WHEN 'HOUSING' THEN 'HOUSING_COMMUNICATION'
    WHEN 'COMMUNICATION' THEN 'HOUSING_COMMUNICATION'
    WHEN 'SUBSCRIPTION' THEN 'HOBBY_LEISURE'
    WHEN 'EDUCATION' THEN 'JOB_PREPARATION'
    WHEN 'CERTIFICATE' THEN 'JOB_PREPARATION'
    WHEN 'ETC_EXPENSE' THEN 'OTHER_FINANCE'
    ELSE `SIMULATION_ITEM_EXPENSE_CATEGORY`
END;

ALTER TABLE `TRANSACTION`
    MODIFY COLUMN `EXPENSE_CATEGORY`
        ENUM('FOOD', 'ALCOHOL_ENTERTAINMENT', 'CAFE_SNACK', 'JOB_PREPARATION', 'SHOPPING',
             'HOBBY_LEISURE', 'HOUSING_COMMUNICATION', 'TRANSPORT_FUEL', 'HEALTH_FITNESS',
             'OTHER_FINANCE') NULL;

ALTER TABLE `SIMULATION_ITEM`
    MODIFY COLUMN `SIMULATION_ITEM_EXPENSE_CATEGORY`
        ENUM('FOOD', 'ALCOHOL_ENTERTAINMENT', 'CAFE_SNACK', 'JOB_PREPARATION', 'SHOPPING',
             'HOBBY_LEISURE', 'HOUSING_COMMUNICATION', 'TRANSPORT_FUEL', 'HEALTH_FITNESS',
             'OTHER_FINANCE') NULL;
