CREATE TABLE `MERCHANT_CATEGORY_MAPPING` (
    `MERCHANT_CATEGORY_MAPPING_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `MAPPING_TYPE` ENUM('MERCHANT_REGNO', 'MERCHANT_CATEGORY_CODE') NOT NULL,
    `MAPPING_VALUE` VARCHAR(50) NOT NULL,
    `EXPENSE_CATEGORY`
        ENUM('FOOD', 'ALCOHOL_ENTERTAINMENT', 'CAFE_SNACK', 'JOB_PREPARATION',
             'SHOPPING', 'HOBBY_LEISURE', 'HOUSING_COMMUNICATION', 'TRANSPORT_FUEL',
             'HEALTH_FITNESS', 'OTHER_FINANCE') NOT NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`MERCHANT_CATEGORY_MAPPING_ID`),
    -- 이 유일 키가 MAPPING_TYPE + MAPPING_VALUE 조건의 조회 인덱스로도 사용된다.
    UNIQUE KEY `UK_MERCHANT_CATEGORY_MAPPING_TYPE_VALUE` (`MAPPING_TYPE`, `MAPPING_VALUE`)
) ENGINE=InnoDB;

INSERT INTO `MERCHANT_CATEGORY_MAPPING` (
    `MAPPING_TYPE`, `MAPPING_VALUE`, `EXPENSE_CATEGORY`
) VALUES
    ('MERCHANT_REGNO', '900-00-00001', 'CAFE_SNACK'),
    ('MERCHANT_REGNO', '900-00-00002', 'FOOD'),
    ('MERCHANT_REGNO', '900-00-00003', 'HOBBY_LEISURE'),
    ('MERCHANT_REGNO', '900-00-00004', 'TRANSPORT_FUEL'),
    ('MERCHANT_REGNO', '900-00-00005', 'SHOPPING'),
    ('MERCHANT_REGNO', '900-00-00006', 'FOOD'),
    ('MERCHANT_REGNO', '900-00-00007', 'SHOPPING'),
    ('MERCHANT_REGNO', '900-00-00008', 'TRANSPORT_FUEL'),
    ('MERCHANT_REGNO', '900-00-00009', 'JOB_PREPARATION'),
    ('MERCHANT_REGNO', '900-00-00010', 'SHOPPING'),
    ('MERCHANT_REGNO', '900-00-00011', 'ALCOHOL_ENTERTAINMENT'),
    ('MERCHANT_REGNO', '900-00-00012', 'HOBBY_LEISURE'),
    ('MERCHANT_REGNO', '900-00-00013', 'HEALTH_FITNESS'),
    ('MERCHANT_REGNO', '900-00-00014', 'HEALTH_FITNESS'),
    ('MERCHANT_REGNO', '900-00-00015', 'SHOPPING'),
    ('MERCHANT_REGNO', '900-00-00016', 'JOB_PREPARATION'),
    ('MERCHANT_REGNO', '900-00-00017', 'HEALTH_FITNESS'),
    ('MERCHANT_REGNO', '900-00-00018', 'HOBBY_LEISURE'),
    ('MERCHANT_REGNO', '900-00-00019', 'FOOD'),
    ('MERCHANT_REGNO', '900-00-00020', 'FOOD'),
    ('MERCHANT_CATEGORY_CODE', '5411', 'FOOD'),
    ('MERCHANT_CATEGORY_CODE', '5812', 'CAFE_SNACK'),
    ('MERCHANT_CATEGORY_CODE', '5814', 'FOOD'),
    ('MERCHANT_CATEGORY_CODE', '4111', 'TRANSPORT_FUEL'),
    ('MERCHANT_CATEGORY_CODE', '5541', 'TRANSPORT_FUEL'),
    ('MERCHANT_CATEGORY_CODE', '4899', 'HOBBY_LEISURE'),
    ('MERCHANT_CATEGORY_CODE', '5942', 'JOB_PREPARATION'),
    ('MERCHANT_CATEGORY_CODE', '5813', 'ALCOHOL_ENTERTAINMENT'),
    ('MERCHANT_CATEGORY_CODE', '7011', 'HOBBY_LEISURE'),
    ('MERCHANT_CATEGORY_CODE', '8099', 'HEALTH_FITNESS'),
    ('MERCHANT_CATEGORY_CODE', '7997', 'HEALTH_FITNESS'),
    ('MERCHANT_CATEGORY_CODE', '7230', 'SHOPPING'),
    ('MERCHANT_CATEGORY_CODE', '8299', 'JOB_PREPARATION'),
    ('MERCHANT_CATEGORY_CODE', '4511', 'HOBBY_LEISURE');
