DELETE FROM `MERCHANT_CATEGORY_MAPPING`
WHERE `MAPPING_TYPE` = 'MERCHANT_CATEGORY_CODE';

ALTER TABLE `MERCHANT_CATEGORY_MAPPING`
    MODIFY COLUMN `MAPPING_TYPE` ENUM('MERCHANT_REGNO', 'MERCHANT_NAME') NOT NULL,
    MODIFY COLUMN `MAPPING_VALUE` VARCHAR(100) NOT NULL;

INSERT INTO `MERCHANT_CATEGORY_MAPPING` (
    `MAPPING_TYPE`, `MAPPING_VALUE`, `EXPENSE_CATEGORY`
) VALUES
    ('MERCHANT_NAME', '스타벅스 강남역점', 'CAFE_SNACK'),
    ('MERCHANT_NAME', '마켓컬리', 'FOOD'),
    ('MERCHANT_NAME', '넷플릭스', 'HOBBY_LEISURE'),
    ('MERCHANT_NAME', '서울교통공사', 'TRANSPORT_FUEL'),
    ('MERCHANT_NAME', '올리브영 홍대점', 'SHOPPING'),
    ('MERCHANT_NAME', '배달의민족', 'FOOD'),
    ('MERCHANT_NAME', '무신사', 'SHOPPING'),
    ('MERCHANT_NAME', 'SK에너지 역삼주유소', 'TRANSPORT_FUEL'),
    ('MERCHANT_NAME', '교보문고 광화문점', 'JOB_PREPARATION'),
    ('MERCHANT_NAME', '쿠팡', 'SHOPPING'),
    ('MERCHANT_NAME', '을지로 포차', 'ALCOHOL_ENTERTAINMENT'),
    ('MERCHANT_NAME', 'NOL 인터파크', 'HOBBY_LEISURE'),
    ('MERCHANT_NAME', '서울튼튼병원', 'HEALTH_FITNESS'),
    ('MERCHANT_NAME', '바디채널 피트니스', 'HEALTH_FITNESS'),
    ('MERCHANT_NAME', '준오헤어 강남점', 'SHOPPING'),
    ('MERCHANT_NAME', '해커스어학원', 'JOB_PREPARATION'),
    ('MERCHANT_NAME', '종로약국', 'HEALTH_FITNESS'),
    ('MERCHANT_NAME', '대한항공', 'HOBBY_LEISURE'),
    ('MERCHANT_NAME', '성수다이닝', 'FOOD'),
    ('MERCHANT_NAME', 'GS25 편의점', 'FOOD');

ALTER TABLE `TRANSACTION`
    MODIFY COLUMN `CLASSIFICATION_METHOD`
        ENUM('MERCHANT_REGNO', 'MERCHANT_CATEGORY_CODE', 'MERCHANT_NAME',
             'ACCOUNT_INFLOW', 'USER_CONFIRMED', 'UNCLASSIFIED', 'MANUAL')
        NOT NULL DEFAULT 'MANUAL';

UPDATE `TRANSACTION` AS `t`
LEFT JOIN `MERCHANT_CATEGORY_MAPPING` AS `m`
    ON `m`.`MAPPING_TYPE` = 'MERCHANT_NAME'
    AND UPPER(REGEXP_REPLACE(TRIM(`m`.`MAPPING_VALUE`), '[[:space:]]+', ' '))
        = UPPER(REGEXP_REPLACE(TRIM(`t`.`MERCHANT_NAME`), '[[:space:]]+', ' '))
    AND `m`.`EXPENSE_CATEGORY` = `t`.`EXPENSE_CATEGORY`
    AND `m`.`IS_ACTIVE` = TRUE
SET `t`.`CLASSIFICATION_METHOD` = CASE
    WHEN `m`.`MERCHANT_CATEGORY_MAPPING_ID` IS NULL THEN 'UNCLASSIFIED'
    ELSE 'MERCHANT_NAME'
END
WHERE `t`.`CLASSIFICATION_METHOD` = 'MERCHANT_CATEGORY_CODE';

ALTER TABLE `TRANSACTION`
    MODIFY COLUMN `CLASSIFICATION_METHOD`
        ENUM('MERCHANT_REGNO', 'MERCHANT_NAME', 'ACCOUNT_INFLOW',
             'USER_CONFIRMED', 'UNCLASSIFIED', 'MANUAL')
        NOT NULL DEFAULT 'MANUAL',
    DROP COLUMN `MERCHANT_CATEGORY_CODE`;
