-- V14의 가맹점명 폴백 매핑도 등록번호 매핑과 같은 최신 분류를 사용한다.
INSERT INTO `MERCHANT_CATEGORY_MAPPING` (
    `MAPPING_TYPE`, `MAPPING_VALUE`, `EXPENSE_CATEGORY`
) VALUES
    ('MERCHANT_NAME', '올리브영 홍대점', 'HEALTH_FITNESS'),
    ('MERCHANT_NAME', '교보문고 광화문점', 'HOBBY_LEISURE'),
    ('MERCHANT_NAME', '준오헤어 강남점', 'HEALTH_FITNESS')
ON DUPLICATE KEY UPDATE
    `EXPENSE_CATEGORY` = VALUES(`EXPENSE_CATEGORY`),
    `IS_ACTIVE` = TRUE;
