-- Buttie MySQL 8.x 테이블 생성 스크립트
-- 기준: 테이블 명세서 v1.0.0 (최종, (3))
-- 데이터베이스: buttie
--
-- 주의:
-- 1) USER, TRANSACTION, LOG은 예약어 혼동 방지를 위해 백틱(`)으로 감쌌습니다.
-- 2) 컬럼명은 v1.0.0 규칙(테이블 프리픽스)을 따릅니다.
-- 3) USER의 버티 정보(경험치·레벨)는 별도 1:1 테이블 USER_BUTTIE로 분리했습니다.
-- 4) ACCOUNT/CARD의 마이데이터 연결 컬럼(CONNECTION_ID)이 명세서에서 빠져 제거했고, UNIQUE는 (USER_ID, EXTERNAL_*)로 구성했습니다.
-- 5) 모든 도메인 이벤트 이력은 단일 LOG 테이블로 통합.
-- 6) 시뮬레이션 관련 날짜는 전부 DATE(LocalDate)로 통일 (SIMULATION 시작/종료, SIMULATION_ITEM 적용 시작/종료).

SET NAMES utf8mb4;
SET time_zone = '+09:00';

-- =========================================================
-- 기존 테이블 초기화가 필요한 경우 아래 주석을 해제하세요. (운영 금지)
-- =========================================================
-- SET FOREIGN_KEY_CHECKS = 0;
-- DROP TABLE IF EXISTS `LOG`;
-- DROP TABLE IF EXISTS `QUEST`;
-- DROP TABLE IF EXISTS `NOTIFICATION`;
-- DROP TABLE IF EXISTS `PROJECTION`;
-- DROP TABLE IF EXISTS `SIMULATION_ITEM`;
-- DROP TABLE IF EXISTS `SIMULATION`;
-- DROP TABLE IF EXISTS `POLICY`;
-- DROP TABLE IF EXISTS `SNAPSHOT`;
-- DROP TABLE IF EXISTS `TRANSACTION`;
-- DROP TABLE IF EXISTS `CARD`;
-- DROP TABLE IF EXISTS `ACCOUNT`;
-- DROP TABLE IF EXISTS `MYDATA`;
-- DROP TABLE IF EXISTS `USER_CONSENTS`;
-- DROP TABLE IF EXISTS `EMPLOYMENT_PREPARATIONS`;
-- DROP TABLE IF EXISTS `USER_BUTTIE`;
-- DROP TABLE IF EXISTS `USER`;
-- DROP TABLE IF EXISTS `ADMIN`;
-- DROP TABLE IF EXISTS `BUTTIE_LEVEL`;
-- SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================
-- 1. 버티 레벨 (BUTTIE_LEVEL)
-- =========================================================
CREATE TABLE IF NOT EXISTS `BUTTIE_LEVEL` (
    `LEVEL` INT NOT NULL,
    `STAGE_NAME` VARCHAR(50) NOT NULL,
    `REQUIRED_EXP` INT NOT NULL,
    `LEVEL_DESCRIPTION` VARCHAR(200) NULL,
    `IMAGE_URL_STABLE` VARCHAR(500) NOT NULL,
    `IMAGE_URL_CAUTION` VARCHAR(500) NOT NULL,
    `IMAGE_URL_DANGER` VARCHAR(500) NOT NULL,
    `LEVEL_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LEVEL_UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`LEVEL`),
    UNIQUE KEY `UK_BUTTIE_LEVEL_REQUIRED_EXP` (`REQUIRED_EXP`),
    CONSTRAINT `CK_BUTTIE_LEVEL_LEVEL` CHECK (`LEVEL` > 0),
    CONSTRAINT `CK_BUTTIE_LEVEL_REQUIRED_EXP` CHECK (`REQUIRED_EXP` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 2. 관리자 (ADMIN)
-- =========================================================
CREATE TABLE IF NOT EXISTS `ADMIN` (
    `ADMIN_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `ADMIN_EMAIL` VARCHAR(100) NOT NULL,
    `ADMIN_PASSWORD_HASH` VARCHAR(255) NOT NULL,
    `ADMIN_ROLE` ENUM('SUPER_ADMIN', 'OPERATOR') NOT NULL DEFAULT 'OPERATOR',
    `ADMIN_STATUS` ENUM('ACTIVE', 'LOCKED', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    `ADMIN_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ADMIN_UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`ADMIN_ID`),
    UNIQUE KEY `UK_ADMIN_EMAIL` (`ADMIN_EMAIL`)
) ENGINE=InnoDB;

-- =========================================================
-- 3. 사용자 (USER)
-- =========================================================
CREATE TABLE IF NOT EXISTS `USER` (
    `USER_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(30) NOT NULL,
    `USER_EMAIL` VARCHAR(100) NOT NULL,
    `USER_PASSWORD_HASH` VARCHAR(255) NOT NULL,
    `USER_NICKNAME` VARCHAR(30) NOT NULL,
    `USER_PHONE_NUMBER` VARCHAR(20) NOT NULL,
    `USER_ONBOARDING_COMPLETED` BOOLEAN NOT NULL DEFAULT FALSE,
    `USER_STATUS` ENUM('ACTIVE', 'LOCKED', 'WITHDRAWN') NOT NULL DEFAULT 'ACTIVE',
    `USER_WITHDRAWN_AT` DATETIME NULL,
    `USER_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `USER_UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`USER_ID`),
    UNIQUE KEY `UK_USER_EMAIL` (`USER_EMAIL`),
    UNIQUE KEY `UK_USER_NICKNAME` (`USER_NICKNAME`),
    UNIQUE KEY `UK_USER_PHONE_NUMBER` (`USER_PHONE_NUMBER`),
    KEY `IDX_USER_STATUS` (`USER_STATUS`),

    CONSTRAINT `CK_USER_WITHDRAWN_AT`
        CHECK (
            (`USER_STATUS` = 'WITHDRAWN' AND `USER_WITHDRAWN_AT` IS NOT NULL)
            OR (`USER_STATUS` <> 'WITHDRAWN')
        )
) ENGINE=InnoDB;

-- =========================================================
-- 4. 사용자 버티 정보 (USER_BUTTIE) - USER와 1:1
-- =========================================================
CREATE TABLE IF NOT EXISTS `USER_BUTTIE` (
    `USER_ID` BIGINT NOT NULL,
    `BUTTIE_TOTAL_EXP` INT NOT NULL DEFAULT 0,
    `BUTTIE_LEVEL` INT NOT NULL DEFAULT 1,

    PRIMARY KEY (`USER_ID`),
    KEY `IDX_USER_BUTTIE_LEVEL` (`BUTTIE_LEVEL`),

    CONSTRAINT `FK_USER_BUTTIE_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_USER_BUTTIE_LEVEL`
        FOREIGN KEY (`BUTTIE_LEVEL`) REFERENCES `BUTTIE_LEVEL` (`LEVEL`)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `CK_USER_BUTTIE_TOTAL_EXP` CHECK (`BUTTIE_TOTAL_EXP` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 5. 취업 준비 정보 (EMPLOYMENT_PREPARATIONS) - USER와 1:1
-- =========================================================
CREATE TABLE IF NOT EXISTS `EMPLOYMENT_PREPARATIONS` (
    `USER_ID` BIGINT NOT NULL,
    `BIRTH_DATE` DATE NOT NULL,
    `EMPLOYMENT_PREP_REGION` VARCHAR(50) NOT NULL,
    `FAMILY_COUNT` INT NOT NULL DEFAULT 1,
    `EMPLOYMENT_PREP_TYPE` ENUM('FIRST_JOB', 'REEMPLOYMENT') NOT NULL,
    `PREP_START_DATE` DATE NOT NULL,
    `TARGET_EMPLOYMENT_DATE` DATE NOT NULL,
    `LIVING_FUND_THRESHOLD` INT NOT NULL DEFAULT 0,

    PRIMARY KEY (`USER_ID`),
    KEY `IDX_EMPLOYMENT_PREP_REGION` (`EMPLOYMENT_PREP_REGION`),
    KEY `IDX_EMPLOYMENT_PREP_TYPE` (`EMPLOYMENT_PREP_TYPE`),

    CONSTRAINT `FK_EMPLOYMENT_PREP_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `CK_EMPLOYMENT_PREP_FAMILY_COUNT` CHECK (`FAMILY_COUNT` >= 1),
    CONSTRAINT `CK_EMPLOYMENT_PREP_TARGET_DATE`
        CHECK (`TARGET_EMPLOYMENT_DATE` >= `PREP_START_DATE`),
    CONSTRAINT `CK_EMPLOYMENT_PREP_LIVING_FUND` CHECK (`LIVING_FUND_THRESHOLD` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 6. 사용자 약관 동의 (USER_CONSENTS) - USER와 1:1
-- =========================================================
CREATE TABLE IF NOT EXISTS `USER_CONSENTS` (
    `USER_ID` BIGINT NOT NULL,
    `TERMS_AGREED_AT` DATETIME NOT NULL,
    `PRIVACY_AGREED_AT` DATETIME NOT NULL,
    `FINANCIAL_INFO_AGREED_AT` DATETIME NOT NULL,

    PRIMARY KEY (`USER_ID`),
    CONSTRAINT `FK_USER_CONSENTS_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 7. 마이데이터 연결 (MYDATA)
-- =========================================================
CREATE TABLE IF NOT EXISTS `MYDATA` (
    `MYDATA_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `PROVIDER` VARCHAR(50) NOT NULL,
    `REFRESH_TOKEN_ENCRYPTED` TEXT NOT NULL,
    `REFRESH_TOKEN_EXPIRES_AT` DATETIME NULL,
    `MYDATA_STATUS`
        ENUM('CONNECTING', 'CONNECTED', 'EXPIRED', 'REVOKED', 'FAILED')
        NOT NULL DEFAULT 'CONNECTING',
    `LAST_SYNCED_AT` DATETIME NULL,

    PRIMARY KEY (`MYDATA_ID`),
    UNIQUE KEY `UK_MYDATA_USER_PROVIDER` (`USER_ID`, `PROVIDER`),
    KEY `IDX_MYDATA_STATUS` (`MYDATA_STATUS`),

    CONSTRAINT `FK_MYDATA_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 8. 계좌 (ACCOUNT)
-- =========================================================
CREATE TABLE IF NOT EXISTS `ACCOUNT` (
    `ACCOUNT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `EXTERNAL_ACCOUNT_ID` VARCHAR(100) NOT NULL,
    `INSTITUTION_NAME` VARCHAR(100) NOT NULL,
    `ACCOUNT_NAME` VARCHAR(100) NOT NULL,
    `ACCOUNT_TYPE` ENUM('CHECKING', 'SAVINGS', 'DEPOSIT', 'LOAN', 'CARD') NOT NULL,
    `ACCOUNT_NUMBER_MASKED` VARCHAR(50) NULL,
    `BALANCE` INT NOT NULL DEFAULT 0,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `SYNCED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`ACCOUNT_ID`),
    UNIQUE KEY `UK_ACCOUNT_USER_EXTERNAL` (`USER_ID`, `EXTERNAL_ACCOUNT_ID`),
    KEY `IDX_ACCOUNT_TYPE` (`ACCOUNT_TYPE`),
    KEY `IDX_ACCOUNT_IS_ACTIVE` (`IS_ACTIVE`),

    CONSTRAINT `FK_ACCOUNT_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 9. 카드 (CARD)
-- =========================================================
CREATE TABLE IF NOT EXISTS `CARD` (
    `CARD_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `EXTERNAL_CARD_ID` VARCHAR(100) NOT NULL,
    `CARD_INSTITUTION_NAME` VARCHAR(100) NOT NULL,
    `CARD_NAME` VARCHAR(100) NOT NULL,
    `CARD_TYPE` ENUM('CREDIT', 'DEBIT', 'PREPAID') NOT NULL,
    `CARD_NUMBER_MASKED` VARCHAR(50) NULL,
    `CARD_BALANCE` INT NOT NULL DEFAULT 0,
    `CARD_IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `CARD_SYNCED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`CARD_ID`),
    UNIQUE KEY `UK_CARD_USER_EXTERNAL` (`USER_ID`, `EXTERNAL_CARD_ID`),
    KEY `IDX_CARD_IS_ACTIVE` (`CARD_IS_ACTIVE`),

    CONSTRAINT `FK_CARD_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 10. 거래 (TRANSACTION)
-- =========================================================
CREATE TABLE IF NOT EXISTS `TRANSACTION` (
    `TRANSACTION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ACCOUNT_ID` BIGINT NULL,
    `EXTERNAL_TRANSACTION_ID` VARCHAR(100) NULL,
    `TRANSACTION_CONTENT` VARCHAR(255) NOT NULL,
    `TRANSACTION_TYPE` ENUM('EXPENSE', 'INCOME', 'FIXED') NOT NULL,
    `EXPENSE_CATEGORY`
        ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'COMMUNICATION',
             'SUBSCRIPTION', 'EDUCATION', 'CERTIFICATE', 'ETC_EXPENSE')
        NOT NULL DEFAULT 'ETC_EXPENSE',
    `TRANSACTION_AMOUNT` INT NOT NULL,
    `TRANSACTION_AT` DATETIME NOT NULL,
    `TRANSACTION_MEMO` VARCHAR(500) NULL,
    `ANALYSIS_EXCLUDED` BOOLEAN NOT NULL DEFAULT FALSE,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,
    `TRANSACTION_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `TRANSACTION_UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`TRANSACTION_ID`),
    UNIQUE KEY `UK_TRANSACTION_ACCOUNT_EXTERNAL`
        (`ACCOUNT_ID`, `EXTERNAL_TRANSACTION_ID`),
    KEY `IDX_TRANSACTION_USER_AT` (`USER_ID`, `TRANSACTION_AT`),
    KEY `IDX_TRANSACTION_ACCOUNT_ID` (`ACCOUNT_ID`),
    KEY `IDX_TRANSACTION_TYPE` (`TRANSACTION_TYPE`),
    KEY `IDX_TRANSACTION_CATEGORY` (`EXPENSE_CATEGORY`),
    KEY `IDX_TRANSACTION_IS_DELETED` (`IS_DELETED`),

    CONSTRAINT `FK_TRANSACTION_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_TRANSACTION_ACCOUNT`
        FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ACCOUNT_ID`)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `CK_TRANSACTION_AMOUNT` CHECK (`TRANSACTION_AMOUNT` > 0)
) ENGINE=InnoDB;

-- =========================================================
-- 11. 재정 스냅샷 (SNAPSHOT)
-- =========================================================
CREATE TABLE IF NOT EXISTS `SNAPSHOT` (
    `SNAPSHOT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `SNAPSHOT_BASE_DATE` DATE NOT NULL,
    `LIQUID_ASSETS` INT NOT NULL DEFAULT 0,
    `MONTHLY_NET_CASHFLOW` INT NOT NULL DEFAULT 0,
    `PREP_POSSIBLE_MONTHS` DECIMAL(5, 2) NULL,
    `AVG_WEEKEND_EXPENSE` DECIMAL(15, 2) NOT NULL DEFAULT 0,
    `AVG_WEEKEND_INCOME` DECIMAL(15, 2) NOT NULL DEFAULT 0,
    `AVG_WEEK_EXPENSE` DECIMAL(15, 2) NOT NULL DEFAULT 0,
    `AVG_WEEK_INCOME` DECIMAL(15, 2) NOT NULL DEFAULT 0,
    `RISK_LEVEL` ENUM('STABLE', 'CAUTION', 'DANGER') NOT NULL DEFAULT 'STABLE',
    `SNAPSHOT_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`SNAPSHOT_ID`),
    UNIQUE KEY `UK_SNAPSHOT_USER_BASE_DATE` (`USER_ID`, `SNAPSHOT_BASE_DATE`),
    KEY `IDX_SNAPSHOT_RISK_LEVEL` (`RISK_LEVEL`),

    CONSTRAINT `FK_SNAPSHOT_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `CK_SNAPSHOT_LIQUID_ASSETS` CHECK (`LIQUID_ASSETS` >= 0),
    CONSTRAINT `CK_SNAPSHOT_PREP_POSSIBLE_MONTHS`
        CHECK (`PREP_POSSIBLE_MONTHS` IS NULL OR `PREP_POSSIBLE_MONTHS` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 12. 정부 지원 정책 (POLICY)
-- =========================================================
CREATE TABLE IF NOT EXISTS `POLICY` (
    `POLICY_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `POLICY_NAME` VARCHAR(200) NOT NULL,
    `POLICY_CATEGORY` VARCHAR(50) NOT NULL,
    `POLICY_MIN_AGE` INT NULL,
    `POLICY_MAX_AGE` INT NULL,
    `POLICY_REGION` VARCHAR(50) NULL,
    `POLICY_SUPPORT_AMOUNT` INT NULL,
    `DUE_DATE` DATETIME NOT NULL,
    `REQUIRED_DOCUMENT` TEXT NULL,
    `EMPLOYMENT_PREP_STATUS` VARCHAR(50) NULL,
    `FAMILY_COUNT` INT NOT NULL DEFAULT 1,
    `POLICY_STATUS` ENUM('AVAILABLE', 'CLOSED') NOT NULL DEFAULT 'AVAILABLE',
    `POLICY_URL` VARCHAR(500) NULL,

    PRIMARY KEY (`POLICY_ID`),
    KEY `IDX_POLICY_CATEGORY_STATUS` (`POLICY_CATEGORY`, `POLICY_STATUS`),
    KEY `IDX_POLICY_REGION` (`POLICY_REGION`),
    KEY `IDX_POLICY_DUE_DATE` (`DUE_DATE`),
    KEY `IDX_POLICY_AGE` (`POLICY_MIN_AGE`, `POLICY_MAX_AGE`),

    CONSTRAINT `CK_POLICY_AGE_RANGE`
        CHECK (
            (`POLICY_MIN_AGE` IS NULL OR `POLICY_MIN_AGE` >= 0)
            AND (`POLICY_MAX_AGE` IS NULL OR `POLICY_MAX_AGE` >= 0)
            AND (`POLICY_MIN_AGE` IS NULL OR `POLICY_MAX_AGE` IS NULL
                 OR `POLICY_MAX_AGE` >= `POLICY_MIN_AGE`)
        ),
    CONSTRAINT `CK_POLICY_SUPPORT_AMOUNT`
        CHECK (`POLICY_SUPPORT_AMOUNT` IS NULL OR `POLICY_SUPPORT_AMOUNT` >= 0),
    CONSTRAINT `CK_POLICY_FAMILY_COUNT` CHECK (`FAMILY_COUNT` >= 1)
) ENGINE=InnoDB;

-- =========================================================
-- 13. 시뮬레이션 (SIMULATION)  * 시작/종료일 DATE(LocalDate)
-- =========================================================
CREATE TABLE IF NOT EXISTS `SIMULATION` (
    `SIMULATION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `SNAPSHOT_ID` BIGINT NOT NULL,
    `SIMULATION_START_DATE` DATE NOT NULL,
    `SIMULATION_DUE_DATE` DATE NOT NULL,
    `SIMULATION_END_AMOUNT` INT NOT NULL,
    `PREP_MONTHS` DECIMAL(5, 2) NULL,
    `CONFIRMED_AT` TIMESTAMP NULL,
    `ACTIVE_USER_ID` BIGINT
        GENERATED ALWAYS AS (
            CASE
                WHEN `CONFIRMED_AT` IS NULL THEN `USER_ID`
                ELSE NULL
            END
        ) STORED,

    PRIMARY KEY (`SIMULATION_ID`),
    UNIQUE KEY `UK_SIMULATION_ACTIVE_USER` (`ACTIVE_USER_ID`),
    KEY `IDX_SIMULATION_USER` (`USER_ID`),
    KEY `IDX_SIMULATION_SNAPSHOT_ID` (`SNAPSHOT_ID`),

    CONSTRAINT `FK_SIMULATION_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_SIMULATION_SNAPSHOT`
        FOREIGN KEY (`SNAPSHOT_ID`) REFERENCES `SNAPSHOT` (`SNAPSHOT_ID`)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `CK_SIMULATION_DATE_RANGE`
        CHECK (`SIMULATION_DUE_DATE` >= `SIMULATION_START_DATE`),
    CONSTRAINT `CK_SIMULATION_PREP_MONTHS`
        CHECK (`PREP_MONTHS` IS NULL OR `PREP_MONTHS` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 14. 시뮬레이션 적용 항목 (SIMULATION_ITEM)  * 적용 시작/종료일 DATE(LocalDate)
-- =========================================================
CREATE TABLE IF NOT EXISTS `SIMULATION_ITEM` (
    `SIMULATION_ITEM_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SIMULATION_ID` BIGINT NOT NULL,
    `SIMULATION_ITEM_CATEGORY` ENUM('POLICY', 'EXPENSE', 'INCOME') NOT NULL,
    `SIMULATION_ITEM_APPLY_AMOUNT` INT NOT NULL DEFAULT 0,
    `APPLY_START_DATE` DATE NOT NULL,
    `APPLY_END_DATE` DATE NULL,
    `POLICY_ID` BIGINT NULL,
    `DETAIL_VALUE` TEXT NULL,
    `RECURRENCE_TYPE` ENUM('ONCE', 'WEEKLY', 'MONTHLY') NOT NULL DEFAULT 'ONCE',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (`SIMULATION_ITEM_ID`),
    KEY `IDX_SIMULATION_ITEM_SIMULATION_ID` (`SIMULATION_ID`),
    KEY `IDX_SIMULATION_ITEM_CATEGORY` (`SIMULATION_ITEM_CATEGORY`),
    KEY `IDX_SIMULATION_ITEM_POLICY_ID` (`POLICY_ID`),
    KEY `IDX_SIMULATION_ITEM_IS_DELETED` (`IS_DELETED`),

    CONSTRAINT `FK_SIMULATION_ITEM_SIMULATION`
        FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATION` (`SIMULATION_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_SIMULATION_ITEM_POLICY`
        FOREIGN KEY (`POLICY_ID`) REFERENCES `POLICY` (`POLICY_ID`)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `CK_SIMULATION_ITEM_DATE_RANGE`
        CHECK (`APPLY_END_DATE` IS NULL OR `APPLY_END_DATE` >= `APPLY_START_DATE`),
    CONSTRAINT `CK_SIMULATION_ITEM_REFERENCE`
        CHECK (
            (`SIMULATION_ITEM_CATEGORY` = 'POLICY' AND `POLICY_ID` IS NOT NULL)
            OR (`SIMULATION_ITEM_CATEGORY` <> 'POLICY' AND `POLICY_ID` IS NULL)
        )
) ENGINE=InnoDB;

-- =========================================================
-- 15. 월별 예상 결과 (PROJECTION)
-- =========================================================
CREATE TABLE IF NOT EXISTS `PROJECTION` (
    `PROJECTION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SIMULATION_ID` BIGINT NOT NULL,
    `PROJECTION_MONTH` DATE NOT NULL,
    `OPENING_BALANCE` INT NOT NULL DEFAULT 0,
    `EXPECTED_INCOME` INT NOT NULL DEFAULT 0,
    `EXPECTED_EXPENSE` INT NOT NULL DEFAULT 0,
    `CLOSING_BALANCE` INT NOT NULL DEFAULT 0,
    `ADJUSTMENT_REQUIRED` BOOLEAN NOT NULL DEFAULT FALSE,
    `ADJUSTMENT_REASON` VARCHAR(500) NULL,

    PRIMARY KEY (`PROJECTION_ID`),
    UNIQUE KEY `UK_PROJECTION_SIMULATION_MONTH` (`SIMULATION_ID`, `PROJECTION_MONTH`),
    KEY `IDX_PROJECTION_ADJUSTMENT_REQUIRED` (`ADJUSTMENT_REQUIRED`),

    CONSTRAINT `FK_PROJECTION_SIMULATION`
        FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATION` (`SIMULATION_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `CK_PROJECTION_EXPECTED_INCOME` CHECK (`EXPECTED_INCOME` >= 0),
    CONSTRAINT `CK_PROJECTION_EXPECTED_EXPENSE` CHECK (`EXPECTED_EXPENSE` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 16. 알림 (NOTIFICATION)
-- =========================================================
CREATE TABLE IF NOT EXISTS `NOTIFICATION` (
    `NOTIFICATION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `NOTIFICATION_TYPE` ENUM('QUEST', 'POLICY', 'FINANCIAL_CHANGE', 'REWARD') NOT NULL,
    `NOTIFICATION_TITLE` VARCHAR(100) NOT NULL,
    `NOTIFICATION_CONTENT` VARCHAR(1000) NOT NULL,
    `NOTIFICATION_URL` VARCHAR(500) NULL,
    `IS_READ` BOOLEAN NOT NULL DEFAULT FALSE,
    `NOTIFICATION_CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`NOTIFICATION_ID`),
    KEY `IDX_NOTIFICATION_USER_READ_CREATED`
        (`USER_ID`, `IS_READ`, `NOTIFICATION_CREATED_AT`),
    KEY `IDX_NOTIFICATION_TYPE` (`NOTIFICATION_TYPE`),

    CONSTRAINT `FK_NOTIFICATION_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 17. 퀘스트 (QUEST)
-- =========================================================
CREATE TABLE IF NOT EXISTS `QUEST` (
    `QUEST_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `SIMULATION_ID` BIGINT NOT NULL,
    `SIMULATION_ITEM_ID` BIGINT NOT NULL,
    `TRANSACTION_ID` BIGINT NULL,
    `QUEST_TYPE` ENUM('APPLY', 'SUBMIT', 'CANCEL', 'CHECK', 'ETC') NOT NULL,
    `QUEST_TITLE` VARCHAR(100) NOT NULL,
    `QUEST_DESCRIPTION` TEXT NULL,
    `QUEST_DEADLINE` DATETIME NULL,
    `QUEST_STATUS` ENUM('NOT_COMPLETED', 'COMPLETED') NOT NULL DEFAULT 'NOT_COMPLETED',
    `QUEST_URL` VARCHAR(500) NULL,
    `EXP_REWARD` INT NULL DEFAULT 0,
    `QUEST_COMPLETED_AT` DATETIME NULL,

    PRIMARY KEY (`QUEST_ID`),
    KEY `IDX_QUEST_USER_STATUS_DEADLINE` (`USER_ID`, `QUEST_STATUS`, `QUEST_DEADLINE`),
    KEY `IDX_QUEST_SIMULATION_ID` (`SIMULATION_ID`),
    KEY `IDX_QUEST_SIMULATION_ITEM_ID` (`SIMULATION_ITEM_ID`),
    KEY `IDX_QUEST_TRANSACTION_ID` (`TRANSACTION_ID`),

    CONSTRAINT `FK_QUEST_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_QUEST_SIMULATION`
        FOREIGN KEY (`SIMULATION_ID`) REFERENCES `SIMULATION` (`SIMULATION_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_QUEST_SIMULATION_ITEM`
        FOREIGN KEY (`SIMULATION_ITEM_ID`) REFERENCES `SIMULATION_ITEM` (`SIMULATION_ITEM_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `FK_QUEST_TRANSACTION`
        FOREIGN KEY (`TRANSACTION_ID`) REFERENCES `TRANSACTION` (`TRANSACTION_ID`)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `CK_QUEST_EXP_REWARD` CHECK (`EXP_REWARD` IS NULL OR `EXP_REWARD` >= 0),
    CONSTRAINT `CK_QUEST_COMPLETED_AT`
        CHECK (
            (`QUEST_STATUS` = 'COMPLETED' AND `QUEST_COMPLETED_AT` IS NOT NULL)
            OR (`QUEST_STATUS` <> 'COMPLETED')
        )
) ENGINE=InnoDB;

-- =========================================================
-- 18. 로그 (LOG) - 도메인 이벤트 통합 이력
-- =========================================================
CREATE TABLE IF NOT EXISTS `LOG` (
    `LOG_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NULL,
    `ENTITY_TYPE` VARCHAR(50) NOT NULL,
    `ENTITY_ID` BIGINT NULL,
    `ACTION` VARCHAR(50) NOT NULL,
    `LOG_DETAIL` JSON NULL,
    `LOG_CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`LOG_ID`),
    KEY `IDX_LOG_USER_CREATED` (`USER_ID`, `LOG_CREATED_AT`),
    KEY `IDX_LOG_ENTITY` (`ENTITY_TYPE`, `ENTITY_ID`),
    KEY `IDX_LOG_ACTION` (`ACTION`),
    KEY `IDX_LOG_CREATED_AT` (`LOG_CREATED_AT`),

    CONSTRAINT `FK_LOG_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;
