-- Buttie MySQL 8.x 테이블 생성 스크립트
-- 기준: 테이블 명세서 v0.0.3
-- 데이터베이스: buttie
--
-- 주의:
-- 1) USER, TRANSACTION은 MySQL에서 혼동될 수 있어 백틱(`)으로 감쌌습니다.
-- 2) 명세서의 거래 카테고리 기본값 'ETC'는 ENUM 값과 맞지 않아 'ETC_EXPENSE'로 정리했습니다.
-- 3) ACCOUNT의 외부 계좌 복합 UNIQUE는 (MYDATA_ID, EXTERNAL_ACCOUNT_ID)로 구성했습니다.
-- 4) UPDATED_AT / MODIFIED_AT은 수정 시 자동 갱신되도록 설정했습니다.
-- 5) SIMULATION_ITEM의 POLICY_ID / FINANCE_ID는 CHECK 제약조건과 충돌하지 않도록 FK 갱신·삭제 동작을 RESTRICT로 설정했습니다.

SET NAMES utf8mb4;
SET time_zone = '+09:00';

-- =========================================================
-- 기존 테이블 초기화가 필요한 경우 아래 주석을 해제하세요.
-- 운영 환경에서는 사용하지 마세요.
-- =========================================================
-- SET FOREIGN_KEY_CHECKS = 0;
-- DROP TABLE IF EXISTS `QUEST`;
-- DROP TABLE IF EXISTS `NOTIFICATION`;
-- DROP TABLE IF EXISTS `PROJECTION`;
-- DROP TABLE IF EXISTS `SIMULATION_ITEM`;
-- DROP TABLE IF EXISTS `SIMULATION`;
-- DROP TABLE IF EXISTS `SNAPSHOT`;
-- DROP TABLE IF EXISTS `CUSTOM_EXPENSE`;
-- DROP TABLE IF EXISTS `TRANSACTION`;
-- DROP TABLE IF EXISTS `ACCOUNT`;
-- DROP TABLE IF EXISTS `MYDATA`;
-- DROP TABLE IF EXISTS `USER_CONSENTS`;
-- DROP TABLE IF EXISTS `EMPLOYMENT_PREPARATIONS`;
-- DROP TABLE IF EXISTS `USER`;
-- DROP TABLE IF EXISTS `POLICY`;
-- DROP TABLE IF EXISTS `FINANCE`;
-- DROP TABLE IF EXISTS `ADMIN`;
-- DROP TABLE IF EXISTS `BUTTIE_LEVEL`;
-- SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================
-- 1. 버티 레벨
-- =========================================================
CREATE TABLE IF NOT EXISTS `BUTTIE_LEVEL` (
    `LEVEL` INT NOT NULL,
    `STAGE_NAME` VARCHAR(50) NOT NULL,
    `REQUIRED_EXP` INT NOT NULL,
    `DESCRIPTION` VARCHAR(200) NULL,
    `IMAGE_URL_STABLE` VARCHAR(500) NOT NULL,
    `IMAGE_URL_CAUTION` VARCHAR(500) NOT NULL,
    `IMAGE_URL_DANGER` VARCHAR(500) NOT NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`LEVEL`),
    UNIQUE KEY `UK_BUTTIE_LEVEL_REQUIRED_EXP` (`REQUIRED_EXP`),
    CONSTRAINT `CK_BUTTIE_LEVEL_LEVEL`
        CHECK (`LEVEL` > 0),
    CONSTRAINT `CK_BUTTIE_LEVEL_REQUIRED_EXP`
        CHECK (`REQUIRED_EXP` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 2. 관리자
-- =========================================================
CREATE TABLE IF NOT EXISTS `ADMIN` (
    `ADMIN_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `ADMIN_ROLE` ENUM('SUPER_ADMIN', 'OPERATOR')
        NOT NULL DEFAULT 'OPERATOR',
    `STATUS` ENUM('ACTIVE', 'LOCKED', 'INACTIVE')
        NOT NULL DEFAULT 'ACTIVE',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`ADMIN_ID`),
    UNIQUE KEY `UK_ADMIN_EMAIL` (`EMAIL`)
) ENGINE=InnoDB;

-- =========================================================
-- 3. 사용자
-- =========================================================
CREATE TABLE IF NOT EXISTS `USER` (
    `USER_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(30) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `NICKNAME` VARCHAR(30) NOT NULL,
    `PHONE_NUMBER` VARCHAR(20) NOT NULL,
    `ONBOARDING_COMPLETED` BOOLEAN NOT NULL DEFAULT FALSE,
    `STATUS` ENUM('ACTIVE', 'LOCKED', 'WITHDRAWN')
        NOT NULL DEFAULT 'ACTIVE',
    `BUTTIE_TOTAL_EXP` INT NOT NULL DEFAULT 0,
    `BUTTIE_LEVEL` INT NOT NULL DEFAULT 1,
    `WITHDRAWN_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`USER_ID`),
    UNIQUE KEY `UK_USER_EMAIL` (`EMAIL`),
    UNIQUE KEY `UK_USER_NICKNAME` (`NICKNAME`),
    UNIQUE KEY `UK_USER_PHONE_NUMBER` (`PHONE_NUMBER`),
    KEY `IDX_USER_STATUS` (`STATUS`),
    KEY `IDX_USER_BUTTIE_LEVEL` (`BUTTIE_LEVEL`),

    CONSTRAINT `FK_USER_BUTTIE_LEVEL`
        FOREIGN KEY (`BUTTIE_LEVEL`)
        REFERENCES `BUTTIE_LEVEL` (`LEVEL`)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT `CK_USER_BUTTIE_TOTAL_EXP`
        CHECK (`BUTTIE_TOTAL_EXP` >= 0),

    CONSTRAINT `CK_USER_WITHDRAWN_AT`
        CHECK (
            (`STATUS` = 'WITHDRAWN' AND `WITHDRAWN_AT` IS NOT NULL)
            OR
            (`STATUS` <> 'WITHDRAWN')
        )
) ENGINE=InnoDB;

-- =========================================================
-- 4. 취업 준비 정보
-- 사용자와 1:1
-- =========================================================
CREATE TABLE IF NOT EXISTS `EMPLOYMENT_PREPARATIONS` (
    `USER_ID` BIGINT NOT NULL,
    `BIRTH_DATE` DATE NOT NULL,
    `REGION` VARCHAR(50) NOT NULL,
    `FAMILY_COUNT` INT NOT NULL DEFAULT 1,
    `EMPLOYMENT_PREP_TYPE`
        ENUM('FIRST_JOB', 'REEMPLOYMENT', 'JOB_CHANGE') NOT NULL,
    `PREP_START_DATE` DATE NOT NULL,
    `TARGET_EMPLOYMENT_DATE` DATE NOT NULL,
    `LIVING_FUND_THRESHOLD` INT NOT NULL DEFAULT 0,
    `EMERGENCY_FUND_THRESHOLD` INT NOT NULL DEFAULT 0,

    PRIMARY KEY (`USER_ID`),
    KEY `IDX_EMPLOYMENT_PREPARATIONS_REGION` (`REGION`),
    KEY `IDX_EMPLOYMENT_PREPARATIONS_TYPE` (`EMPLOYMENT_PREP_TYPE`),

    CONSTRAINT `FK_EMPLOYMENT_PREPARATIONS_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `CK_EMPLOYMENT_PREPARATIONS_FAMILY_COUNT`
        CHECK (`FAMILY_COUNT` >= 1),
    CONSTRAINT `CK_EMPLOYMENT_PREPARATIONS_TARGET_DATE`
        CHECK (`TARGET_EMPLOYMENT_DATE` >= `PREP_START_DATE`),
    CONSTRAINT `CK_EMPLOYMENT_PREPARATIONS_LIVING_FUND`
        CHECK (`LIVING_FUND_THRESHOLD` >= 0),
    CONSTRAINT `CK_EMPLOYMENT_PREPARATIONS_EMERGENCY_FUND`
        CHECK (`EMERGENCY_FUND_THRESHOLD` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 5. 사용자 약관 동의
-- 사용자와 1:1
-- =========================================================
CREATE TABLE IF NOT EXISTS `USER_CONSENTS` (
    `USER_ID` BIGINT NOT NULL,
    `TERMS_AGREED_AT` DATETIME NOT NULL,
    `PRIVACY_AGREED_AT` DATETIME NOT NULL,
    `FINANCIAL_INFO_AGREED_AT` DATETIME NOT NULL,

    PRIMARY KEY (`USER_ID`),

    CONSTRAINT `FK_USER_CONSENTS_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 6. 마이데이터 연결
-- =========================================================
CREATE TABLE IF NOT EXISTS `MYDATA` (
    `MYDATA_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `PROVIDER` VARCHAR(50) NOT NULL,
    `PROVIDER_USER_ID` VARCHAR(255) NOT NULL,
    `REFRESH_TOKEN_ENCRYPTED` TEXT NOT NULL,
    `ACCESS_TOKEN_EXPIRES_AT` DATETIME NULL,
    `REFRESH_TOKEN_EXPIRES_AT` DATETIME NULL,
    `SCOPE` VARCHAR(500) NULL,
    `STATUS`
        ENUM('CONNECTING', 'CONNECTED', 'EXPIRED', 'REVOKED', 'FAILED')
        NOT NULL DEFAULT 'CONNECTING',
    `LAST_TOKEN_REFRESHED_AT` DATETIME NULL,
    `LAST_SYNCED_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`MYDATA_ID`),
    UNIQUE KEY `UK_MYDATA_USER_PROVIDER` (`USER_ID`, `PROVIDER`),
    KEY `IDX_MYDATA_STATUS` (`STATUS`),

    CONSTRAINT `FK_MYDATA_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 7. 계좌
-- =========================================================
CREATE TABLE IF NOT EXISTS `ACCOUNT` (
    `ACCOUNT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `MYDATA_ID` BIGINT NULL,
    `EXTERNAL_ACCOUNT_ID` VARCHAR(100) NOT NULL,
    `INSTITUTION_NAME` VARCHAR(100) NOT NULL,
    `ACCOUNT_NAME` VARCHAR(100) NOT NULL,
    `ACCOUNT_TYPE`
        ENUM('CHECKING', 'SAVINGS', 'DEPOSIT', 'LOAN', 'CARD') NOT NULL,
    `ACCOUNT_NUMBER_MASKED` VARCHAR(50) NULL,
    `BALANCE` INT NOT NULL DEFAULT 0,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `SYNCED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`ACCOUNT_ID`),
    UNIQUE KEY `UK_ACCOUNT_MYDATA_EXTERNAL`
        (`MYDATA_ID`, `EXTERNAL_ACCOUNT_ID`),
    KEY `IDX_ACCOUNT_USER_ID` (`USER_ID`),
    KEY `IDX_ACCOUNT_TYPE` (`ACCOUNT_TYPE`),
    KEY `IDX_ACCOUNT_IS_ACTIVE` (`IS_ACTIVE`),

    CONSTRAINT `FK_ACCOUNT_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_ACCOUNT_MYDATA`
        FOREIGN KEY (`MYDATA_ID`)
        REFERENCES `MYDATA` (`MYDATA_ID`)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB;

-- =========================================================
-- 8. 거래
-- =========================================================
CREATE TABLE IF NOT EXISTS `TRANSACTION` (
    `TRANSACTION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ACCOUNT_ID` BIGINT NULL,
    `EXTERNAL_TRANSACTION_ID` VARCHAR(100) NULL,
    `CONTENT` VARCHAR(255) NOT NULL,
    `IS_EXPENSE` BOOLEAN NOT NULL DEFAULT FALSE,
    `CATEGORY`
        ENUM(
            'FOOD',
            'TRANSPORT',
            'HOUSING',
            'COMMUNICATION',
            'SUBSCRIPTION',
            'EDUCATION',
            'CERTIFICATE',
            'ETC_EXPENSE'
        ) NOT NULL DEFAULT 'ETC_EXPENSE',
    `AMOUNT` INT NOT NULL,
    `TRANSACTION_AT` DATETIME NOT NULL,
    `MEMO` VARCHAR(500) NULL,
    `ANALYSIS_EXCLUDED` BOOLEAN NOT NULL DEFAULT FALSE,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,
    `DELETED_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`TRANSACTION_ID`),
    UNIQUE KEY `UK_TRANSACTION_ACCOUNT_EXTERNAL`
        (`ACCOUNT_ID`, `EXTERNAL_TRANSACTION_ID`),
    KEY `IDX_TRANSACTION_USER_AT` (`USER_ID`, `TRANSACTION_AT`),
    KEY `IDX_TRANSACTION_ACCOUNT_ID` (`ACCOUNT_ID`),
    KEY `IDX_TRANSACTION_CATEGORY` (`CATEGORY`),
    KEY `IDX_TRANSACTION_IS_EXPENSE` (`IS_EXPENSE`),
    KEY `IDX_TRANSACTION_ANALYSIS_EXCLUDED` (`ANALYSIS_EXCLUDED`),
    KEY `IDX_TRANSACTION_IS_DELETED` (`IS_DELETED`),

    CONSTRAINT `FK_TRANSACTION_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_TRANSACTION_ACCOUNT`
        FOREIGN KEY (`ACCOUNT_ID`)
        REFERENCES `ACCOUNT` (`ACCOUNT_ID`)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT `CK_TRANSACTION_AMOUNT`
        CHECK (`AMOUNT` > 0),

    CONSTRAINT `CK_TRANSACTION_DELETED_AT`
        CHECK (
            (`IS_DELETED` = TRUE AND `DELETED_AT` IS NOT NULL)
            OR
            (`IS_DELETED` = FALSE)
        )
) ENGINE=InnoDB;

-- =========================================================
-- 9. 사용자 설정 비용
-- 고정 지출 및 예정 비용
-- =========================================================
CREATE TABLE IF NOT EXISTS `CUSTOM_EXPENSE` (
    `CUSTOM_EXPENSE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `IS_FIXED` BOOLEAN NOT NULL DEFAULT TRUE,
    `NAME` VARCHAR(100) NOT NULL,
    `CATEGORY` VARCHAR(50) NOT NULL,
    `AMOUNT` INT NOT NULL,
    `EXPECTED_DATE` DATE NOT NULL,
    `IS_RECURRING` BOOLEAN NOT NULL DEFAULT FALSE,
    `RECURRENCE_TYPE` ENUM('WEEKLY', 'MONTHLY') NULL,
    `RECURRENCE_END_DATE` DATE NULL,
    `STATUS` ENUM('ACTIVE', 'COMPLETED', 'CANCELLED')
        NOT NULL DEFAULT 'ACTIVE',
    `MEMO` VARCHAR(500) NULL,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`CUSTOM_EXPENSE_ID`),
    KEY `IDX_CUSTOM_EXPENSE_USER_DATE` (`USER_ID`, `EXPECTED_DATE`),
    KEY `IDX_CUSTOM_EXPENSE_STATUS` (`STATUS`),
    KEY `IDX_CUSTOM_EXPENSE_IS_FIXED` (`IS_FIXED`),

    CONSTRAINT `FK_CUSTOM_EXPENSE_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `CK_CUSTOM_EXPENSE_AMOUNT`
        CHECK (`AMOUNT` > 0),

    CONSTRAINT `CK_CUSTOM_EXPENSE_RECURRENCE`
        CHECK (
            (`IS_RECURRING` = FALSE
                AND `RECURRENCE_TYPE` IS NULL
                AND `RECURRENCE_END_DATE` IS NULL)
            OR
            (`IS_RECURRING` = TRUE
                AND `RECURRENCE_TYPE` IS NOT NULL)
        ),

    CONSTRAINT `CK_CUSTOM_EXPENSE_RECURRENCE_END_DATE`
        CHECK (
            `RECURRENCE_END_DATE` IS NULL
            OR `RECURRENCE_END_DATE` >= `EXPECTED_DATE`
        )
) ENGINE=InnoDB;

-- =========================================================
-- 10. 재정 스냅샷
-- =========================================================
CREATE TABLE IF NOT EXISTS `SNAPSHOT` (
    `SNAPSHOT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `BASE_DATE` DATE NOT NULL,
    `CALCULATION_MONTHS` INT NOT NULL DEFAULT 3,
    `TOTAL_ASSETS` INT NOT NULL DEFAULT 0,
    `LIQUID_ASSETS` INT NOT NULL DEFAULT 0,
    `FINANCIAL_PRODUCT_ASSETS` INT NOT NULL DEFAULT 0,
    `TOTAL_DEBT` INT NOT NULL DEFAULT 0,
    `AVG_MONTHLY_INCOME` INT NOT NULL DEFAULT 0,
    `AVG_MONTHLY_EXPENSE` INT NOT NULL DEFAULT 0,
    `MONTHLY_NET_CASHFLOW` INT NOT NULL DEFAULT 0,
    `PREP_POSSIBLE_MONTHS` DECIMAL(5, 2) NULL,
    `TARGET_BALANCE` INT NOT NULL DEFAULT 0,
    `ADDITIONAL_REQUIRED_AMOUNT` INT NOT NULL DEFAULT 0,
    `TARGET_ACHIEVEMENT_RATE` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `RISK_LEVEL` ENUM('STABLE', 'CAUTION', 'DANGER')
        NOT NULL DEFAULT 'STABLE',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`SNAPSHOT_ID`),
    UNIQUE KEY `UK_SNAPSHOT_USER_BASE_DATE` (`USER_ID`, `BASE_DATE`),
    KEY `IDX_SNAPSHOT_RISK_LEVEL` (`RISK_LEVEL`),

    CONSTRAINT `FK_SNAPSHOT_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `CK_SNAPSHOT_CALCULATION_MONTHS`
        CHECK (`CALCULATION_MONTHS` > 0),
    CONSTRAINT `CK_SNAPSHOT_TOTAL_ASSETS`
        CHECK (`TOTAL_ASSETS` >= 0),
    CONSTRAINT `CK_SNAPSHOT_LIQUID_ASSETS`
        CHECK (`LIQUID_ASSETS` >= 0),
    CONSTRAINT `CK_SNAPSHOT_FINANCIAL_PRODUCT_ASSETS`
        CHECK (`FINANCIAL_PRODUCT_ASSETS` >= 0),
    CONSTRAINT `CK_SNAPSHOT_TOTAL_DEBT`
        CHECK (`TOTAL_DEBT` >= 0),
    CONSTRAINT `CK_SNAPSHOT_AVG_MONTHLY_INCOME`
        CHECK (`AVG_MONTHLY_INCOME` >= 0),
    CONSTRAINT `CK_SNAPSHOT_AVG_MONTHLY_EXPENSE`
        CHECK (`AVG_MONTHLY_EXPENSE` >= 0),
    CONSTRAINT `CK_SNAPSHOT_PREP_POSSIBLE_MONTHS`
        CHECK (`PREP_POSSIBLE_MONTHS` IS NULL OR `PREP_POSSIBLE_MONTHS` >= 0),
    CONSTRAINT `CK_SNAPSHOT_ADDITIONAL_REQUIRED_AMOUNT`
        CHECK (`ADDITIONAL_REQUIRED_AMOUNT` >= 0),
    CONSTRAINT `CK_SNAPSHOT_TARGET_ACHIEVEMENT_RATE`
        CHECK (`TARGET_ACHIEVEMENT_RATE` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 11. 금융 상품
-- =========================================================
CREATE TABLE IF NOT EXISTS `FINANCE` (
    `FINANCE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `COMPANY` VARCHAR(20) NOT NULL,
    `NAME` VARCHAR(200) NOT NULL,
    `TYPE` ENUM('DEPOSIT', 'SAVINGS') NOT NULL,
    `MIN_AGE` INT NULL,
    `MAX_AGE` INT NULL,
    `PERIOD` INT NOT NULL,
    `BASE_RATE` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `PREFERRED_RATE` DECIMAL(5, 2) NULL,
    `MINIMUM_AMOUNT` INT NULL,
    `REGISTER_CONDITION` TEXT NULL,
    `WITHDRAW_CONDITION` TEXT NULL,
    `URL` VARCHAR(500) NULL,
    `STATUS` ENUM('AVAILABLE', 'CLOSED')
        NOT NULL DEFAULT 'AVAILABLE',

    PRIMARY KEY (`FINANCE_ID`),
    KEY `IDX_FINANCE_TYPE_STATUS` (`TYPE`, `STATUS`),
    KEY `IDX_FINANCE_AGE` (`MIN_AGE`, `MAX_AGE`),

    CONSTRAINT `CK_FINANCE_AGE_RANGE`
        CHECK (
            (`MIN_AGE` IS NULL OR `MIN_AGE` >= 0)
            AND
            (`MAX_AGE` IS NULL OR `MAX_AGE` >= 0)
            AND
            (`MIN_AGE` IS NULL OR `MAX_AGE` IS NULL OR `MAX_AGE` >= `MIN_AGE`)
        ),
    CONSTRAINT `CK_FINANCE_PERIOD`
        CHECK (`PERIOD` > 0),
    CONSTRAINT `CK_FINANCE_BASE_RATE`
        CHECK (`BASE_RATE` >= 0),
    CONSTRAINT `CK_FINANCE_PREFERRED_RATE`
        CHECK (`PREFERRED_RATE` IS NULL OR `PREFERRED_RATE` >= 0),
    CONSTRAINT `CK_FINANCE_MINIMUM_AMOUNT`
        CHECK (`MINIMUM_AMOUNT` IS NULL OR `MINIMUM_AMOUNT` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 12. 정부 지원 정책
-- =========================================================
CREATE TABLE IF NOT EXISTS `POLICY` (
    `POLICY_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(200) NOT NULL,
    `CATEGORY` VARCHAR(50) NOT NULL,
    `MIN_AGE` INT NULL,
    `MAX_AGE` INT NULL,
    `REGION` VARCHAR(50) NULL,
    `AMOUNT` INT NULL,
    `DUE_DATE` DATETIME NOT NULL,
    `DOCUMENT` TEXT NULL,
    `EMPLOYMENT_STATUS` VARCHAR(50) NULL,
    `FAMILY_COUNT` INT NOT NULL DEFAULT 1,
    `STATUS` ENUM('AVAILABLE', 'CLOSED')
        NOT NULL DEFAULT 'AVAILABLE',
    `URL` VARCHAR(500) NULL,

    PRIMARY KEY (`POLICY_ID`),
    KEY `IDX_POLICY_CATEGORY_STATUS` (`CATEGORY`, `STATUS`),
    KEY `IDX_POLICY_REGION` (`REGION`),
    KEY `IDX_POLICY_DUE_DATE` (`DUE_DATE`),
    KEY `IDX_POLICY_AGE` (`MIN_AGE`, `MAX_AGE`),

    CONSTRAINT `CK_POLICY_AGE_RANGE`
        CHECK (
            (`MIN_AGE` IS NULL OR `MIN_AGE` >= 0)
            AND
            (`MAX_AGE` IS NULL OR `MAX_AGE` >= 0)
            AND
            (`MIN_AGE` IS NULL OR `MAX_AGE` IS NULL OR `MAX_AGE` >= `MIN_AGE`)
        ),
    CONSTRAINT `CK_POLICY_AMOUNT`
        CHECK (`AMOUNT` IS NULL OR `AMOUNT` >= 0),
    CONSTRAINT `CK_POLICY_FAMILY_COUNT`
        CHECK (`FAMILY_COUNT` >= 1)
) ENGINE=InnoDB;

-- =========================================================
-- 13. 시뮬레이션
-- =========================================================
CREATE TABLE IF NOT EXISTS `SIMULATION` (
    `SIMULATION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `SNAPSHOT_ID` BIGINT NOT NULL,
    `START_DATE` DATETIME NOT NULL,
    `END_DATE` DATETIME NOT NULL,
    `ENDING_BALANCE` INT NOT NULL,
    `TARGET_RATE` DECIMAL(5, 2) NOT NULL,
    `PREP_MONTHS` DECIMAL(5, 2) NULL,
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    `CONFIRMED_AT` TIMESTAMP NULL,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (`SIMULATION_ID`),
    KEY `IDX_SIMULATION_USER_CREATED_AT` (`USER_ID`, `CREATED_AT`),
    KEY `IDX_SIMULATION_SNAPSHOT_ID` (`SNAPSHOT_ID`),
    KEY `IDX_SIMULATION_IS_DELETED` (`IS_DELETED`),

    CONSTRAINT `FK_SIMULATION_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_SIMULATION_SNAPSHOT`
        FOREIGN KEY (`SNAPSHOT_ID`)
        REFERENCES `SNAPSHOT` (`SNAPSHOT_ID`)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT `CK_SIMULATION_DATE_RANGE`
        CHECK (`END_DATE` >= `START_DATE`),
    CONSTRAINT `CK_SIMULATION_TARGET_RATE`
        CHECK (`TARGET_RATE` >= 0),
    CONSTRAINT `CK_SIMULATION_PREP_MONTHS`
        CHECK (`PREP_MONTHS` IS NULL OR `PREP_MONTHS` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 14. 시뮬레이션 적용 항목
-- =========================================================
CREATE TABLE IF NOT EXISTS `SIMULATION_ITEM` (
    `SIMULATION_ITEM_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SIMULATION_ID` BIGINT NOT NULL,
    `CATEGORY` ENUM('POLICY', 'FINANCIAL', 'EXPENSE', 'INCOME') NOT NULL,
    `AMOUNT` INT NOT NULL DEFAULT 0,
    `START_DATE` DATETIME NOT NULL,
    `END_DATE` DATETIME NULL,
    `POLICY_ID` BIGINT NULL,
    `FINANCE_ID` BIGINT NULL,
    `DETAIL_VALUE` TEXT NULL,
    `RECURRENCE_TYPE` ENUM('ONCE', 'WEEKLY', 'MONTHLY')
        NOT NULL DEFAULT 'ONCE',
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (`SIMULATION_ITEM_ID`),
    KEY `IDX_SIMULATION_ITEM_SIMULATION_ID` (`SIMULATION_ID`),
    KEY `IDX_SIMULATION_ITEM_CATEGORY` (`CATEGORY`),
    KEY `IDX_SIMULATION_ITEM_POLICY_ID` (`POLICY_ID`),
    KEY `IDX_SIMULATION_ITEM_FINANCE_ID` (`FINANCE_ID`),
    KEY `IDX_SIMULATION_ITEM_IS_DELETED` (`IS_DELETED`),

    CONSTRAINT `FK_SIMULATION_ITEM_SIMULATION`
        FOREIGN KEY (`SIMULATION_ID`)
        REFERENCES `SIMULATION` (`SIMULATION_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_SIMULATION_ITEM_POLICY`
        FOREIGN KEY (`POLICY_ID`)
        REFERENCES `POLICY` (`POLICY_ID`)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT `FK_SIMULATION_ITEM_FINANCE`
        FOREIGN KEY (`FINANCE_ID`)
        REFERENCES `FINANCE` (`FINANCE_ID`)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT `CK_SIMULATION_ITEM_DATE_RANGE`
        CHECK (`END_DATE` IS NULL OR `END_DATE` >= `START_DATE`),

    CONSTRAINT `CK_SIMULATION_ITEM_REFERENCE`
        CHECK (
            (`CATEGORY` = 'POLICY' AND `POLICY_ID` IS NOT NULL AND `FINANCE_ID` IS NULL)
            OR
            (`CATEGORY` = 'FINANCIAL' AND `FINANCE_ID` IS NOT NULL AND `POLICY_ID` IS NULL)
            OR
            (`CATEGORY` IN ('EXPENSE', 'INCOME')
                AND `POLICY_ID` IS NULL
                AND `FINANCE_ID` IS NULL)
        )
) ENGINE=InnoDB;

-- =========================================================
-- 15. 월별 예상 결과
-- =========================================================
CREATE TABLE IF NOT EXISTS `PROJECTION` (
    `PROJECTION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SIMULATION_ID` BIGINT NOT NULL,
    `PROJECTION_MONTH` DATE NOT NULL,
    `OPENING_BALANCE` INT NOT NULL DEFAULT 0,
    `EXPECTED_INCOME` INT NOT NULL DEFAULT 0,
    `EXPECTED_EXPENSE` INT NOT NULL DEFAULT 0,
    `CLOSING_BALANCE` INT NOT NULL DEFAULT 0,
    `ADJUSTMENT_REQUIRED` BOOLEAN NOT NULL DEFAULT FALSE,
    `ADJUSTMENT_REASON` VARCHAR(500) NULL,

    PRIMARY KEY (`PROJECTION_ID`),
    UNIQUE KEY `UK_PROJECTION_SIMULATION_MONTH`
        (`SIMULATION_ID`, `PROJECTION_MONTH`),
    KEY `IDX_PROJECTION_ADJUSTMENT_REQUIRED` (`ADJUSTMENT_REQUIRED`),

    CONSTRAINT `FK_PROJECTION_SIMULATION`
        FOREIGN KEY (`SIMULATION_ID`)
        REFERENCES `SIMULATION` (`SIMULATION_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `CK_PROJECTION_EXPECTED_INCOME`
        CHECK (`EXPECTED_INCOME` >= 0),
    CONSTRAINT `CK_PROJECTION_EXPECTED_EXPENSE`
        CHECK (`EXPECTED_EXPENSE` >= 0)
) ENGINE=InnoDB;

-- =========================================================
-- 16. 알림
-- =========================================================
CREATE TABLE IF NOT EXISTS `NOTIFICATION` (
    `NOTIFICATION_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `TYPE` ENUM('QUEST', 'POLICY', 'FINANCIAL_CHANGE', 'REWARD') NOT NULL,
    `TITLE` VARCHAR(100) NOT NULL,
    `CONTENT` VARCHAR(1000) NOT NULL,
    `URL` VARCHAR(500) NULL,
    `IS_READ` BOOLEAN NOT NULL DEFAULT FALSE,
    `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`NOTIFICATION_ID`),
    KEY `IDX_NOTIFICATION_USER_READ_CREATED`
        (`USER_ID`, `IS_READ`, `CREATED_AT`),
    KEY `IDX_NOTIFICATION_TYPE` (`TYPE`),

    CONSTRAINT `FK_NOTIFICATION_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- 17. 퀘스트
-- =========================================================
CREATE TABLE IF NOT EXISTS `QUEST` (
    `QUEST_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `SIMULATION_ID` BIGINT NOT NULL,
    `SIMULATION_ITEM_ID` BIGINT NOT NULL,
    `TRANSACTION_ID` BIGINT NULL,
    `QUEST_TYPE` ENUM('APPLY', 'SUBMIT', 'CANCEL', 'CHECK', 'ETC') NOT NULL,
    `TITLE` VARCHAR(100) NOT NULL,
    `DESCRIPTION` TEXT NULL,
    `DEADLINE` DATETIME NULL,
    `STATUS` ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED')
        NOT NULL DEFAULT 'PLANNED',
    `URL` VARCHAR(500) NULL,
    `EXP_REWARD` INT NULL DEFAULT 0,
    `COMPLETED_AT` DATETIME NULL,

    PRIMARY KEY (`QUEST_ID`),
    KEY `IDX_QUEST_USER_STATUS_DEADLINE`
        (`USER_ID`, `STATUS`, `DEADLINE`),
    KEY `IDX_QUEST_SIMULATION_ID` (`SIMULATION_ID`),
    KEY `IDX_QUEST_SIMULATION_ITEM_ID` (`SIMULATION_ITEM_ID`),
    KEY `IDX_QUEST_TRANSACTION_ID` (`TRANSACTION_ID`),

    CONSTRAINT `FK_QUEST_USER`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_QUEST_SIMULATION`
        FOREIGN KEY (`SIMULATION_ID`)
        REFERENCES `SIMULATION` (`SIMULATION_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_QUEST_SIMULATION_ITEM`
        FOREIGN KEY (`SIMULATION_ITEM_ID`)
        REFERENCES `SIMULATION_ITEM` (`SIMULATION_ITEM_ID`)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT `FK_QUEST_TRANSACTION`
        FOREIGN KEY (`TRANSACTION_ID`)
        REFERENCES `TRANSACTION` (`TRANSACTION_ID`)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT `CK_QUEST_EXP_REWARD`
        CHECK (`EXP_REWARD` IS NULL OR `EXP_REWARD` >= 0),

    CONSTRAINT `CK_QUEST_COMPLETED_AT`
        CHECK (
            (`STATUS` = 'COMPLETED' AND `COMPLETED_AT` IS NOT NULL)
            OR
            (`STATUS` <> 'COMPLETED')
        )
) ENGINE=InnoDB;
