ALTER TABLE `SNAPSHOT`
    ADD COLUMN `AVG_MONTHLY_EXPENSE` DECIMAL(15, 2) NOT NULL DEFAULT 0
        AFTER `PREP_POSSIBLE_MONTHS`,
    ADD COLUMN `AVG_MONTHLY_INCOME` DECIMAL(15, 2) NOT NULL DEFAULT 0
        AFTER `AVG_MONTHLY_EXPENSE`;
