ALTER TABLE `SIMULATION_ITEM`
    ADD COLUMN `SIMULATION_ITEM_NAME` VARCHAR(100) NOT NULL DEFAULT ''
        AFTER `SIMULATION_ITEM_CATEGORY`,
    ADD COLUMN `SIMULATION_ITEM_EXPENSE_CATEGORY`
        ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'COMMUNICATION',
             'SUBSCRIPTION', 'EDUCATION', 'CERTIFICATE', 'ETC_EXPENSE')
        NULL
        AFTER `SIMULATION_ITEM_NAME`;

CREATE TABLE IF NOT EXISTS `USER_NOTIFICATION` (
    `USER_ID` BIGINT NOT NULL,
    `POLICY_DEADLINE_NOTIFICATION_YN` BOOLEAN NOT NULL DEFAULT TRUE,
    `FINANCIAL_CHANGE_NOTIFICATION_YN` BOOLEAN NOT NULL DEFAULT TRUE,
    `PLAN_DEVIATION_NOTIFICATION_YN` BOOLEAN NOT NULL DEFAULT TRUE,
    `SERVICE_NOTICE_NOTIFICATION_YN` BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (`USER_ID`),

    CONSTRAINT `FK_USER_NOTIFICATION_USER`
        FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
