ALTER TABLE `SIMULATION_ITEM`
    ADD COLUMN `SIMULATION_ITEM_NAME` VARCHAR(100) NOT NULL DEFAULT ''
        AFTER `SIMULATION_ITEM_CATEGORY`,
    ADD COLUMN `SIMULATION_ITEM_EXPENSE_CATEGORY`
        ENUM('FOOD', 'TRANSPORT', 'HOUSING', 'COMMUNICATION',
             'SUBSCRIPTION', 'EDUCATION', 'CERTIFICATE', 'ETC_EXPENSE')
        NULL
        AFTER `SIMULATION_ITEM_NAME`;
