ALTER TABLE `SNAPSHOT`
    DROP CHECK `CK_SNAPSHOT_PREP_POSSIBLE_MONTHS`;

ALTER TABLE `SNAPSHOT`
    RENAME COLUMN `PREP_POSSIBLE_MONTHS` TO `CURRENT_PREP_MONTHS`;

ALTER TABLE `SNAPSHOT`
    ADD CONSTRAINT `CK_SNAPSHOT_CURRENT_PREP_MONTHS`
        CHECK (`CURRENT_PREP_MONTHS` IS NULL OR `CURRENT_PREP_MONTHS` >= 0);

ALTER TABLE `SIMULATION`
    DROP CHECK `CK_SIMULATION_PREP_MONTHS`;

ALTER TABLE `SIMULATION`
    RENAME COLUMN `PREP_MONTHS` TO `EXPECT_PREP_MONTHS`;

ALTER TABLE `SIMULATION`
    ADD CONSTRAINT `CK_SIMULATION_EXPECT_PREP_MONTHS`
        CHECK (`EXPECT_PREP_MONTHS` IS NULL OR `EXPECT_PREP_MONTHS` >= 0);
